# Install required libraries
!pip install ultralytics
!pip install torch
!pip install onnxruntime
!pip install roboflow

# Import OS and get current working directory
import os
HOME = os.getcwd()
print(HOME)

# Create a datasets directory inside current workspace
!mkdir {HOME}/datasets

# Move into datasets directory
%cd {HOME}/datasets

# Install Roboflow again (safe to ensure availability in Colab)
!pip install roboflow --quiet

# Import Roboflow and initialize with API key
from roboflow import Roboflow
rf = Roboflow(api_key="HI42QRXkU9xSlq7DHhks")

# Load the specific workspace and project
project = rf.workspace("ai-project-i3wje").project("waste-detection-vqkjo")

# Download dataset version 9 in YOLOv8 format
dataset = project.version(9).download("yolov8")

# Install additional dependencies for model export
!pip install ultralytics
!pip install onnx

# Import YOLO and ONNX library
from ultralytics import YOLO
import onnx

# Initialize a YOLOv8 nano model architecture (from scratch config)
model = YOLO('yolov8n.yaml')

# Load pretrained YOLOv8 nano weights (recommended for faster training)
model = YOLO('yolov8n.pt')

# Path to dataset configuration file (data.yaml)
path = '/content/datasets/waste-detection-9/data.yaml'

# Train the model on custom dataset
# epochs=50 means training will run 50 full passes over dataset
results = model.train(data=path, epochs=50)

# Validate the trained model on validation dataset
results = model.val()

# Export trained model to ONNX format (for deployment/inference)
success = model.export(format='onnx')

import shutil

# Path of training output folder generated by YOLO
source_folder = '/content/datasets/runs/detect/train'

# Name of ZIP file to be created
zip_filename = '/content/train.zip'

# Compress training results into a ZIP file
shutil.make_archive(zip_filename[:-4], 'zip', source_folder)

# Download the ZIP file from Colab to local machine
from google.colab import files
files.download(zip_filename)